import { bigint, index, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { user } from './auth.ts';
import { todo } from './todo.ts';

/**
 * Files attached to a todo.
 *
 * The row and the blob are separate systems, and they can disagree. Deleting a todo
 * cascades this row away immediately — a dangling *row* pointing at a missing file is what
 * users see — while the blob itself is removed by a background job. The reverse (blob gone
 * first, row remaining) would show a broken download; this way the worst case is an
 * unreferenced blob costing storage until the sweeper runs.
 *
 * `storage_key` is generated by `@keel/storage`, never derived from the uploaded filename.
 * `filename` is only ever displayed and re-offered on download.
 */
export const attachment = pgTable(
  'attachment',
  {
    id: text('id').primaryKey(),
    todoId: text('todo_id')
      .notNull()
      .references(() => todo.id, { onDelete: 'cascade' }),
    /** Who uploaded it. Access is decided by the todo's list, as everywhere else. */
    uploadedBy: text('uploaded_by')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    filename: text('filename').notNull(),
    contentType: text('content_type').notNull(),
    /** bigint: a 2GB file overflows a 32-bit integer, and someone will try. */
    size: bigint('size', { mode: 'number' }).notNull(),
    storageKey: text('storage_key').notNull(),
    digest: text('digest').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (table) => [index('attachment_todo_idx').on(table.todoId)],
);

/**
 * Blobs whose row is gone, waiting to be swept.
 *
 * Written by the same statement that deletes an attachment, so the intent to delete the
 * blob is recorded transactionally with the row's removal. Without this, a crash between
 * "row deleted" and "blob deleted" leaks a file nothing will ever look for again.
 */
export const orphanedBlob = pgTable('orphaned_blob', {
  storageKey: text('storage_key').primaryKey(),
  createdAt: timestamp('created_at', { withTimezone: true })
    .$defaultFn(() => new Date())
    .notNull(),
});

export const attachmentTables = { attachment, orphanedBlob };
