import { customType } from 'drizzle-orm/pg-core';

/**
 * Postgres `tsvector`.
 *
 * Drizzle has no built-in column type for it, and a custom type is a better fit than
 * pretending it is text: this column is never read into JavaScript and never written from
 * it — it is generated by the database and only ever appears inside a `@@` match or a
 * `ts_rank` call.
 *
 * Typed as `string` because that is what a driver would hand back if anyone did select it.
 * Nobody should.
 */
export const tsvector = customType<{ data: string; driverData: string }>({
  dataType: () => 'tsvector',
});
