#!/usr/bin/env node
/**
 * Bring up the local development database, and make the environment it needs.
 *
 * A clean checkout has no `.env` — deliberately, so the gate passes without secrets. But
 * that leaves the application unrunnable, and the README's instructions assume a database
 * appears from somewhere. This closes that gap: one command, no account anywhere.
 */
import { execFileSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const envFile = path.join(root, '.env');
const DEV_URL = 'postgres://keel:keel@localhost:5432/keel';

function run(cmd, args) {
  return execFileSync(cmd, args, {
    cwd: root,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

// 1. Docker must exist AND its daemon must be running. Checking `docker --version` is
//    not enough — the CLI is installed independently of the daemon, and the failure then
//    surfaces as an unreadable socket error from `docker compose`.
const fallback =
  'Alternatively, point DATABASE_URL at any Postgres you already have (a hosted\n' +
  `instance works fine) by putting it in .env:\n\n  DATABASE_URL="${DEV_URL}"\n`;

try {
  run('docker', ['--version']);
} catch {
  console.error(`Docker is not installed.\n\nInstall Docker Desktop, or:\n\n${fallback}`);
  process.exit(1);
}

try {
  run('docker', ['info']);
} catch {
  console.error(
    'Docker is installed but its daemon is not running.\n\n' +
      'Start Docker Desktop and run `pnpm db:up` again.\n' +
      (process.platform === 'darwin' ? '  open -a Docker\n' : '') +
      `\n${fallback}`,
  );
  process.exit(1);
}

/*
 * Development-only defaults.
 *
 * Every one of these is a variable whose absence makes a working feature *look* broken
 * rather than fail loudly: the queue endpoint refuses every request without JOBS_SECRET,
 * and a webhook cannot point at the developer's own machine without the private-host
 * hatch. A local environment that cannot exercise a feature is one where nobody tests it.
 *
 * `WEBHOOK_ALLOW_PRIVATE_HOSTS` is refused outright by the environment contract when
 * NODE_ENV is production, so this cannot follow a copied `.env` into a deployment.
 */
const devDefaults = () => ({
  DATABASE_URL: `"${DEV_URL}"`,
  BETTER_AUTH_SECRET: `"${crypto.randomBytes(32).toString('base64')}"`,
  BETTER_AUTH_URL: '"http://localhost:3000"',
  JOBS_SECRET: `"${crypto.randomBytes(24).toString('hex')}"`,
  WEBHOOK_ALLOW_PRIVATE_HOSTS: '1',
});

// 2. Create .env if absent. A generated secret beats a placeholder nobody replaces.
if (!fs.existsSync(envFile)) {
  const body = Object.entries(devDefaults())
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');
  fs.writeFileSync(
    envFile,
    `# Generated by \`pnpm db:up\`. Safe to edit; never commit.\n${body}\n`,
  );
  console.log('created .env with generated secrets');
} else {
  /*
   * An existing .env is not overwritten, but it is topped up. Otherwise every developer
   * who set the file up before a variable existed silently lacks it, and the feature that
   * needs it appears broken on their machine only.
   */
  const existing = fs.readFileSync(envFile, 'utf8');
  const missing = Object.entries(devDefaults()).filter(
    ([key]) => !new RegExp(`^\\s*${key}=`, 'm').test(existing),
  );
  if (missing.length > 0) {
    fs.appendFileSync(
      envFile,
      `\n# Added by \`pnpm db:up\`.\n` +
        missing.map(([key, value]) => `${key}=${value}`).join('\n') +
        '\n',
    );
    console.log(`.env topped up with ${missing.map(([key]) => key).join(', ')}`);
  } else {
    console.log('.env already exists — leaving it alone');
  }
}

// 3. Start Postgres and wait for it to actually accept connections.
console.log('starting postgres…');
try {
  run('docker', ['compose', 'up', '-d', '--wait', 'postgres']);
} catch (error) {
  console.error('docker compose failed:\n');
  console.error(error.stderr || error.stdout || String(error));
  process.exit(1);
}

console.log(`postgres ready on localhost:5432\n\nNext:\n  pnpm db:migrate\n  pnpm dev`);
